images:
  - name: cilium-agent
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/cilium
    tag: v1.13.1
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'high'
        availability_requirement: 'high'
  - name: cilium-operator
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/operator
    tag: v1.13.1
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'high'
        availability_requirement: 'low'
  - name: hubble-ui
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-ui
    tag: v0.10.0
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'low'
        availability_requirement: 'low'
  - name: hubble-ui-backend
    sourceRepository: github.com/cilium/hubble-ui-backend
    repository: quay.io/cilium/hubble-ui-backend
    tag: v0.10.0
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'low'
        availability_requirement: 'low'
  - name: hubble-relay
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-relay
    tag: v1.13.1
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'low'
        availability_requirement: 'low'
  - name: certgen
    sourceRepository: github.com/cilium/certgen
    repository: quay.io/cilium/certgen
    tag: v0.1.8
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'protected'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'high'
        integrity_requirement: 'high'
        availability_requirement: 'low'
  - name: kube-proxy
    sourceRepository: github.com/kubernetes/kubernetes
    repository: registry.k8s.io/kube-proxy
  - name: portmap-copier
    sourceRepository: github.com/gardener/portmap-copier
    repository: eu.gcr.io/gardener-project/gardener/portmap-copier
    tag: v0.2.0
    labels:
    - name: 'gardener.cloud/cve-categorisation'
      value:
        network_exposure: 'private'
        authentication_enforced: false
        user_interaction: 'end-user'
        confidentiality_requirement: 'low'
        integrity_requirement: 'high'
        availability_requirement: 'low'
