images:
  - name: cilium-agent
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/cilium
    tag: v1.8.0
  - name: cilium-preflight
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/cilium
    tag: v1.8.0
  - name: cilium-operator
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/operator
    tag: v1.8.0
  - name: cilium-etcd-operator
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/cilium-etcd-operator
    tag: v2.0.7
  - name: cilium-nodeinit
    sourceRepository: github.com/cilium/cilium
    repository: gcr.io/google-containers/startup-script
    tag: v1
  - name: hubble-ui
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-ui
    tag: v0.6.0
  - name: hubble-relay
    sourceRepository: github.com/cilium/hubble-ui
    repository: docker.io/cilium/hubble-relay
    tag: v1.8.0