images:
  - name: cilium-agent
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/cilium
    tag: v1.12.4
  - name: cilium-preflight
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/cilium
    tag: v1.12.4
  - name: cilium-operator
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/operator
    tag: v1.12.4
  - name: cilium-etcd-operator
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/cilium-etcd-operator
    tag: v2.0.7
  - name: cilium-nodeinit
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/startup-script
    tag: v3
  - name: hubble-ui
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-ui
    tag: v0.9.2
  - name: hubble-ui-backend
    sourceRepository: github.com/cilium/hubble-ui-backend
    repository: quay.io/cilium/hubble-ui-backend
    tag: v0.9.2
  - name: hubble-relay
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-relay
    tag: v1.12.4
  - name: certgen
    sourceRepository: github.com/cilium/certgen
    repository: quay.io/cilium/certgen
    tag: v0.1.8
  - name: kube-proxy
    sourceRepository: github.com/kubernetes/kubernetes
    repository: registry.k8s.io/kube-proxy
  - name: portmap-copier
    sourceRepository: github.com/gardener/portmap-copier
    repository: eu.gcr.io/gardener-project/gardener/portmap-copier
    tag: v0.2.0
