images:
  - name: cilium-agent
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/cilium
    tag: v1.11.5
  - name: cilium-preflight
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/cilium
    tag: v1.11.5
  - name: cilium-operator
    sourceRepository: github.com/cilium/cilium
    repository: quay.io/cilium/operator
    tag: v1.11.5
  - name: cilium-etcd-operator
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/cilium-etcd-operator
    tag: v2.0.7
  - name: cilium-nodeinit
    sourceRepository: github.com/cilium/cilium
    repository: docker.io/cilium/startup-script
    tag: v3
  - name: hubble-ui
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-ui
    tag: v0.8.5
  - name: hubble-ui-backend
    sourceRepository: github.com/cilium/hubble-ui-backend
    repository: quay.io/cilium/hubble-ui-backend
    tag: v0.8.5
  - name: envoy
    sourceRepository: github.com/envoyproxy/envoy
    repository: docker.io/envoyproxy/envoy
    tag: v1.18.4
  - name: hubble-relay
    sourceRepository: github.com/cilium/hubble-ui
    repository: quay.io/cilium/hubble-relay
    tag: v1.11.5
  - name: certgen
    sourceRepository: github.com/cilium/certgen
    repository: quay.io/cilium/certgen
    tag: v0.1.5
  - name: kube-proxy
    sourceRepository: github.com/kubernetes/kubernetes
    repository: k8s.gcr.io/hyperkube
    targetVersion: "< 1.17"
  - name: kube-proxy
    sourceRepository: github.com/kubernetes/kubernetes
    repository: k8s.gcr.io/kube-proxy
    targetVersion: ">= 1.17"
