---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: hubble-generate-certs
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: hubble-generate-certs
    gardener.cloud/role: system-component
    app.kubernetes.io/name: hubble-generate-certs
    app.kubernetes.io/part-of: cilium
spec:
  template:
    metadata:
      labels:
        k8s-app: hubble-generate-certs
    spec:
      containers:
        - name: certgen
          image: {{ index .Values.global.images "certgen" }}
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
          command:
            - "/usr/bin/cilium-certgen"
          # Because this is executed as a job, we pass the values as command
          # line args instead of via config map. This allows users to inspect
          # the values used in past runs by inspecting the completed pod.
          args:
            - "--ca-generate=true"
            - "--ca-reuse-secret"
            - "--ca-secret-namespace=kube-system"
            - "--ca-secret-name=cilium-ca"
            - "--ca-common-name=Cilium CA"
          env:
            - name: CILIUM_CERTGEN_CONFIG
              value: |
                certs:
                - name: hubble-server-certs
                  namespace: kube-system
                  commonName: "*.{{ .Values.global.cluster.name }}.hubble-grpc.cilium.io"
                  hosts:
                  - "*.{{ .Values.global.cluster.name }}.hubble-grpc.cilium.io"
                  usage:
                  - signing
                  - key encipherment
                  - server auth
                  - client auth
                  validity: 26280h
                - name: hubble-relay-client-certs
                  namespace: kube-system
                  commonName: "*.hubble-relay.cilium.io"
                  hosts:
                  - "*.hubble-relay.cilium.io"
                  usage:
                  - signing
                  - key encipherment
                  - client auth
                  validity: 26280h
      hostNetwork: false
      serviceAccount: hubble-generate-certs
      serviceAccountName: hubble-generate-certs
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 86400
